//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using DB.Query.Models.DataAnnotations;

namespace DB.Query.Models.Entities.DBCi
{    
    [Table("CiDepartamento")]
    public class CiDepartamento : DBCi
    {
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Empresa
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Codigo_Empresa")]
        public int CodigoEmpresa { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Codigo")]
        public int Codigo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Departamento
        /// </summary>
        [StringColumnLength("Departamento", 100)]
        public string Departamento { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao_EN
        /// </summary>
        [StringColumnLength("Descricao_EN", 250)]
        public string DescricaoEN { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Gerente
        /// </summary>
        public System.Nullable<int> CodigoGerente { get; set; }
    }
}
