//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



using DB.Query.Models.DataAnnotations;

namespace DB.Query.Models.Entities.Kaizen
{
    
    [Table("Cadastro_Kaizen")]
    public class Cadastro_Kaizen : Kaizen
    {
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo
        /// </summary>
        [PrimaryKey(Identity=true)]
        [RequiredColumn("Codigo")]
        public int Codigo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Sigla
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Sigla")]
        [StringColumnLength("Sigla", 28)]
        public string Sigla { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Lider
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Codigo_Lider")]
        [ColumnAttribute("Codigo_Lider")]
        public int Codigo_Lider { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Area
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Area")]
        public int Area { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Depto
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Depto")]
        public int Depto { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Titulo
        /// </summary>
        [RequiredColumn("Titulo")]
        [StringColumnLength("Titulo", 200)]
        public string Titulo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Gera_Red_Custo
        /// </summary>
        [ColumnAttribute("Gera_Red_Custo")]
        public System.Nullable<bool> Gera_Red_Custo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Valor_Red_Custo_Prev
        /// </summary>
        [ColumnAttribute("Valor_Red_Custo_Prev")]
        public System.Nullable<decimal> Valor_Red_Custo_Prev { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Aprov_Gestor
        /// </summary>
        [ColumnAttribute("Aprov_Gestor")]
        public System.Nullable<bool> Aprov_Gestor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Gestor
        /// </summary>
        [ColumnAttribute("Codigo_Gestor")]
        public System.Nullable<int> Codigo_Gestor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Data_Aprov_Gestor
        /// </summary>
        [ColumnAttribute("Data_Aprov_Gestor")]
        public System.Nullable<System.DateTime> Data_Aprov_Gestor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Observacao_Gestor
        /// </summary>
        [StringColumnLength("Observacao_Gestor", 1000)]
        [ColumnAttribute("Observacao_Gestor")]
        public string Observacao_Gestor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Motivo_Rejeicao
        /// </summary>
        [StringColumnLength("Motivo_Rejeicao", 1000)]
        [ColumnAttribute("Motivo_Rejeicao")]
        public string Motivo_Rejeicao { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Necessita_Aprov_Comite
        /// </summary>
        [ColumnAttribute("Necessita_Aprov_Comite")]
        public System.Nullable<bool> Necessita_Aprov_Comite { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Aprov_Comite
        /// </summary>
        [ColumnAttribute("Aprov_Comite")]
        public System.Nullable<bool> Aprov_Comite { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Usuario_Comite
        /// </summary>
        [ColumnAttribute("Codigo_Usuario_Comite")]
        public System.Nullable<int> Codigo_Usuario_Comite { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Observacao_Comite
        /// </summary>
        [StringColumnLength("Observacao_Comite", 500)]
        [ColumnAttribute("Observacao_Comite")]
        public string Observacao_Comite { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Data_Aprov_Comite
        /// </summary>
        [ColumnAttribute("Data_Aprov_Comite")]
        public System.Nullable<System.DateTime> Data_Aprov_Comite { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Tipo_Kaizen
        /// </summary>
        [ColumnAttribute("Tipo_Kaizen")]
        public System.Nullable<int> Tipo_Kaizen { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Modelo_Kaizen
        /// </summary>
        [ColumnAttribute("Modelo_Kaizen")]
        public System.Nullable<int> Modelo_Kaizen { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Antes
        /// </summary>
        [StringColumnLength("Antes", 1000)]
        public string Antes { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Depois
        /// </summary>
        [StringColumnLength("Depois", 1000)]
        public string Depois { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Problema
        /// </summary>
        [StringColumnLength("Problema", 1000)]
        public string Problema { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Solucao
        /// </summary>
        [StringColumnLength("Solucao", 1000)]
        public string Solucao { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Perda
        /// </summary>
        [StringColumnLength("Perda", 1000)]
        public string Perda { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Beneficios
        /// </summary>
        [StringColumnLength("Beneficios", 1000)]
        public string Beneficios { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Anexo
        /// </summary>
        [StringColumnLength("Anexo", 16)]
        public string Anexo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Status
        /// </summary>
        public System.Nullable<int> Status { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Data
        /// </summary>
        public System.Nullable<System.DateTime> Data { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Pontos
        /// </summary>
        public System.Nullable<decimal> Pontos { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Num_PlanoAcao
        /// </summary>
        [ColumnAttribute("Num_PlanoAcao")]
        public System.Nullable<int> Num_PlanoAcao { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Finalizado
        /// </summary>
        public System.Nullable<bool> Finalizado { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Status_Fisico
        /// </summary>
        [ColumnAttribute("Status_Fisico")]
        public System.Nullable<int> Status_Fisico { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Data_Final
        /// </summary>
        [ColumnAttribute("Data_Final")]
        public System.Nullable<System.DateTime> Data_Final { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ObservacaoWEB
        /// </summary>
        [StringColumnLength("ObservacaoWEB", 16)]
        public string ObservacaoWEB { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de extraido_SICPontos
        /// </summary>
        [ColumnAttribute("extraido_SICPontos")]
        public System.Nullable<bool> extraido_SICPontos { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de RetGestor
        /// </summary>
        [StringColumnLength("RetGestor", 500)]
        public string RetGestor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de codigo_pilar
        /// </summary>
        [ColumnAttribute("codigo_pilar")]
        public System.Nullable<int> codigo_pilar { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de DtValidaRedCusto
        /// </summary>
        public System.Nullable<System.DateTime> DtValidaRedCusto { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de FK_Setor
        /// </summary>
        [ColumnAttribute("FK_Setor")]
        public System.Nullable<int> FK_Setor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de FK_Processo
        /// </summary>
        [ColumnAttribute("FK_Processo")]
        public System.Nullable<int> FK_Processo { get; set; }
    }
}
