//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



using DB.Query.Modelos.Procedures;
using DB.Query.Models.Constants;
using DB.Query.Models.DataAnnotations;
using DB.Query.Models.Procedures.SignCi.Result;

namespace DB.Query.Models.Procedures.SignCi.Parameters
{
    
    [Procedure("PS_ItemDominio")]
    [Database(Databases.SignCi)]
    public class PSItemDominioParameters : PSStoredProcedure<PSItemDominioResult>
    {
        /// <summary>
        /// Propiedade mapeada para a definição de NomeDominio
        /// </summary>
        [Paremeter("NomeDominio", System.Data.SqlDbType.VarChar, 50)]
        public string NomeDominio { get; set; }
    }
}
