//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------


using DB.Query.Models.DataAnnotations;

namespace DB.Query.Models.Procedures.DBCi.Result
{
    
    [Procedure("PS_ItemDominio")]
    public class PSItemDominioResult
    {
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo
        /// </summary>
        public System.Nullable<int> Codigo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Nome
        /// </summary>
        public string Nome { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao
        /// </summary>
        public string Descricao { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Sigla
        /// </summary>
        public string Sigla { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Dominio
        /// </summary>
        public System.Nullable<int> Codigo_Dominio { get; set; }
    }
}
